// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqszBtWaQncL9lDpId-nuFDNNj5bKTSKQ',
    appId: '1:1067105794515:web:691b66df2898101aa81726',
    messagingSenderId: '1067105794515',
    projectId: 'my-tiktok-hobby-app-dev',
    authDomain: 'my-tiktok-hobby-app-dev.firebaseapp.com',
    storageBucket: 'my-tiktok-hobby-app-dev.appspot.com',
    measurementId: 'G-29J71HT55L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2H9AE0MwV8MwM17SrWBDSrWaMbN-cBE',
    appId: '1:1067105794515:android:579735e1b5778d8ba81726',
    messagingSenderId: '1067105794515',
    projectId: 'my-tiktok-hobby-app-dev',
    storageBucket: 'my-tiktok-hobby-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpy46ALNvP4E1cLIdx4sHbA-3igq8YTo',
    appId: '1:1067105794515:ios:a362b4cbf4e0ae92a81726',
    messagingSenderId: '1067105794515',
    projectId: 'my-tiktok-hobby-app-dev',
    storageBucket: 'my-tiktok-hobby-app-dev.appspot.com',
    iosClientId: '1067105794515-21i87egqcaqi4febon7aj18vufvjbh1a.apps.googleusercontent.com',
    iosBundleId: 'com.zhlee1997.my-tiktok-hobby-app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpy46ALNvP4E1cLIdx4sHbA-3igq8YTo',
    appId: '1:1067105794515:ios:a362b4cbf4e0ae92a81726',
    messagingSenderId: '1067105794515',
    projectId: 'my-tiktok-hobby-app-dev',
    storageBucket: 'my-tiktok-hobby-app-dev.appspot.com',
    iosClientId: '1067105794515-21i87egqcaqi4febon7aj18vufvjbh1a.apps.googleusercontent.com',
    iosBundleId: 'com.zhlee1997.my-tiktok-hobby-app.dev',
  );
}
