// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdM7GWi8DBkt44VPF40cJrgJOW4MFnsIs',
    appId: '1:1097098202193:web:9727ad9e7fa844c4cb7c70',
    messagingSenderId: '1097098202193',
    projectId: 'my-tiktok-hobby-app-prod',
    authDomain: 'my-tiktok-hobby-app-prod.firebaseapp.com',
    storageBucket: 'my-tiktok-hobby-app-prod.appspot.com',
    measurementId: 'G-RW5WSP5JQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNCVYhN0rMcfF-ErLn3zMX-FISvAN5_o',
    appId: '1:1097098202193:android:3c093887f6bf6067cb7c70',
    messagingSenderId: '1097098202193',
    projectId: 'my-tiktok-hobby-app-prod',
    storageBucket: 'my-tiktok-hobby-app-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOqlZw_VRENHl_2acqR-0vzv4ePLGCwRQ',
    appId: '1:1097098202193:ios:22d0dd1db93f8050cb7c70',
    messagingSenderId: '1097098202193',
    projectId: 'my-tiktok-hobby-app-prod',
    storageBucket: 'my-tiktok-hobby-app-prod.appspot.com',
    iosClientId: '1097098202193-6gutijiombr00fm4ik4ee8936mg1cdck.apps.googleusercontent.com',
    iosBundleId: 'com.zhlee1997.my-tiktok-hobby-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOqlZw_VRENHl_2acqR-0vzv4ePLGCwRQ',
    appId: '1:1097098202193:ios:22d0dd1db93f8050cb7c70',
    messagingSenderId: '1097098202193',
    projectId: 'my-tiktok-hobby-app-prod',
    storageBucket: 'my-tiktok-hobby-app-prod.appspot.com',
    iosClientId: '1097098202193-6gutijiombr00fm4ik4ee8936mg1cdck.apps.googleusercontent.com',
    iosBundleId: 'com.zhlee1997.my-tiktok-hobby-app',
  );
}
